# -*- coding: utf-8 -*-
"""Exercise 4: Favorite Number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVLSCXfg7oYVBAfjzvNjMYZNcDaVb9sk
"""



#Use a variable to represent your favorite number. Then,using that variable, create a message that reveals your favorite number. Print that message.

favorite_number = (2)

print("My favorite number is", favorite_number)