# -*- coding: utf-8 -*-
"""Exercise 3: stripping names

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVLSCXfg7oYVBAfjzvNjMYZNcDaVb9sk
"""



#Tidy up the code to make it easier to understand
#Use a variable to represent a person’s name, and include some whitespace characters at the beginning and end of the name. Make sure you use each character combination, “\t” and “\n”, at least once.
#Print the name once, so the whitespace around the name is displayed.
#Then print the name using each of the three stripping functions, lstrip(), rstrip(), and strip().

name = '  Angela Beatriz Villapaz  '

print(f'String =\'{name}\'')

print(f'After Removing Leading Whitespace =\'{name.lstrip()}\'')

print(f'After Removing Trailing Whitespaces =\'{name.rstrip()}\'')

print(f'After Trimming Whitespaces =\'{name.strip()}\'')