# -*- coding: utf-8 -*-
"""Exercise 1: Variables

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVLSCXfg7oYVBAfjzvNjMYZNcDaVb9sk
"""



#Type out the code below and add the correct data types to complete the variables
#Assign a message to a variable, and print that message. Then change the value of the variable to a new message, and print the new message.

#Original value for name was "Rafael Formaran"
name = ("Angela Villapaz")

print(name)