# -*- coding: utf-8 -*-
"""Exercise 5: USB shopper

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVLSCXfg7oYVBAfjzvNjMYZNcDaVb9sk
"""



#A girl heads to a computer shop to buy some USB sticks. She loves USB sticks and wants as many as she can get for £50. They are £6 each.
#Write a programme that calculates how many USB sticks she can buy and how many pounds she will have left.
#You will to use the arithmetic operators to complete this exercise.

total_money = (50)
flash_drive = (6)
total_flash_drive = (50//6)
total_change = (50%6)

print("The total number of flash drives she can buy is", total_flash_drive)
print("She will have a total of £",total_change, "left")