# -*- coding: utf-8 -*-
"""Exercise 2: Variables

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVLSCXfg7oYVBAfjzvNjMYZNcDaVb9sk
"""



#Find a quote from a famous person you admire. Print the quote and the name of its author.
#Your output should look something like the following, including the quotation marks:
#Albert Einstein once said, “A person who never made a mistake never tried anything new.

quote = ("Abraham Lincoln once said, \"Those who deny freedom to others, deserve it not for themselves\"")

print(quote)